### ISSUE TITLE
How to implement native 'hidesBottomBarWhenPushed'?

### ISSUE THREAD

**Issue by Vienta** [mhaddl/MHCustomTabBarController#14]
Hi,
I'm using your custom tabbarcontroller,but there is a issue that I want this tabbarcontroller can have a property like `hidesBottomBarWhenPushed` in native.

Did you considered this ?

Regards,
Vienta

**Comment by mhaddl** [comment]
Hi Vianta,

MHCustomTabBarController was built for a specific and simple use case, so I did not consider implementing every feature UITabBarController has. I also do not have any plans to implement this feature, but it should be pretty straight forward to implement something like this yourself.
The tab bar is basically just a view, so you can hide it whenever you want, you just have to manage the showing and hiding yourself.

**Comment by Vienta** [comment]
hiThx for reply.I had implemented it.thanks for your job!

发自Outlook




On Mon, Feb 16, 2015 at 2:26 AM -0800, "Martin Hartl" <notifications@github.com> wrote:












Hi Vianta,



MHCustomTabBarController was built for a specific and simple use case, so I did not consider implementing every feature UITabBarController has. I also do not have any plans to implement this feature, but it should be pretty straight forward to implement something like this yourself.

The tab bar is basically just a view, so you can hide it whenever you want, you just have to manage the showing and hiding yourself.
