### ISSUE TITLE
Error when using on Storyboard

### ISSUE THREAD

**Issue by gonso75** [mhaddl/MHCustomTabBarController#15]
Im trying to use this component in my project, but when I reach in my navigation this container, I get an app crash with this error:

Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UIStoryboardSegueTemplate 0x7fa2b346ebd0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key containerView.'

It was working fine in the demo project, I copied from one storyboard to another and then I got the Crash...

What am I missing?

**Comment by mhaddl** [comment]
Hi,

can you double check if the containerView outlet is correctly connected from the storyboard to the source file? Maybe you renamed the IBOutlet in the source file and the connection isn't set up correctly anymore.
You can check this stuff here: 
http://cl.ly/image/35430V0N362U

**Comment by gonso75** [comment]
Actually, the problem was that since I copied the View Controller from the example project, the outlets were poiting to unexisting View Controllers.  Sorry for that!
