### ISSUE TITLE
selectedViewController and selectedIndex

### ISSUE THREAD

**Issue by f33chobits** [mhaddl/MHCustomTabBarController#16]
Hi, @mhaddl 
    I like this lib because I always use navigationController as the initial viewcontroller in storyboard and TabBarController as the second, because that would save works for animating hiding tabBar. But this would be more convinient if we support selectedViewController and selectedIndex function as UITabBarController, wouldn't it?

**Comment by mhaddl** [comment]
Hi @f33chobits,
I've built this library for a very simple and specific use case, so I don't have plans to implement your suggested features at the moment, but I highly encourage pull requests and would love to merge one into this project.

Have a nice day!
Martin

**Comment by f33chobits** [comment]
Hi Martin
I think this is the best substitute for UITabBarController, cause it would save the efforts to subclass UITabBarController and code the custom tab bar or selection tab image.I always suggest to do UI layout in storyboard or xib. If you don't have the time I can make a pull request for you.But it just matters that you are not online usually.

Nice day~
Wenchao Ding

**Comment by mhaddl** [comment]
Hi,
a pull request would be really nice! I will be more active here on Github again, there was a lot of university stuff going on lately. So if you are sending a pull request, I'll merge it really quick!
Thanks
Martin

**Comment by f33chobits** [comment]
Hi，
OK. It would take some time because it is Chinese New Year right now. I would love  to send this PR for you to review and dicuss it with you~
Thanks
Wenchao Ding

**Comment by mhaddl** [comment]
Alright, have a nice holidays then! :)
The comment section of the pull request will be a good place for the discussion, I think.
I look forward hearing from you again!
