### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by superandrew** [mhaddl/MHCustomTabBarController#21]
When I press a tab, the first time a view gets loaded, it takes some time. Any Idea on why that could happen?

Thank you very much!

**Comment by superandrew** [comment]
any news on this?

thanks!

**Comment by mhaddl** [comment]
Hi!

The ViewControllers for MHCustomTabBarController are lazy loaded. This means, the first time the tab is pressed, the ViewController gets loaded (viewDidLoad is called), after that the ViewController is kept in the memory. To improve the performance you need to optimise the ViewController code, load resources in a background thread etc.

Let me know if you need more information!

Martin

**Comment by superandrew** [comment]
I've read your words, and understand their meaning, but I am far to understand how to implement this logic. You mean I need to subclass MHCustomTabBarController? And in a background thread load my viewcontrollers?

Is this something related to the design of MHCTB or something on a OS level?

Thanks!

**Comment by superandrew** [comment]
hi @mhaddl could you please suggest how and where to implemetn this in MHCustomTabBarController? should I subclass it? which methods should I look into?

thanks

**Comment by superandrew** [comment]
Hello, My problem was totally urelated to MHCustomTabBarController. In facts, it was a font no more used in the app and referenced in the storyboard that created a lazy loading very slow for the lookup of the font. I checked it with time profiler.

Hope it helps!

**Comment by mhaddl** [comment]
Great you found the problem!

Cheers
